# These are supported funding model platforms

github: [tarmo888]
custom: ["https://www.paypal.me/tarmo888", "https://tarmo888.github.io/bb-convert/#amount=5&currency=USD&address=NTYO4ZKPRBPXW6WY2QUMJBPNDLOGX5OJ"]
